<a href="https://colab.research.google.com/github/JayeshHarjule/LetsUpgradeAI-ML/blob/master/Day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Answer 1) Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [9]:
import numpy as np
x = np.array([6, 4, 3])
y = np.array([2, 5, 8])
print("Original numbers:")
print(x)
print(y)
print("Element wise comparison for greater than is:")
print(np.greater(x, y))
print("Element wise comparison for greater than or equal to is:")
print(np.greater_equal(x, y))
print("Element wise comparison for less than is:")
print(np.less(x, y))
print("Element wise comparison for less than or equal to is:")
print(np.less_equal(x, y))

Original numbers:
[6 4 3]
[2 5 8]
Element wise comparison for greater than is:
[ True False False]
Element wise comparison for greater than or equal to is:
[ True False False]
Element wise comparison for less than is:
[False  True  True]
Element wise comparison for less than or equal to is:
[False  True  True]


Answer 2) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [2]:
import numpy as np
array_zero=np.zeros(10)
print("An array of 10 zeros:", array_zero)
array_ones=np.ones(10)
print("An array of 10 ones:",array_ones)
array_fives=np.ones(10)*5
print("An array of 10 fives:",array_fives)

An array of 10 zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives: [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Answer 3) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
given array

In [1]:
import numpy as np
x = np.array([[1,3,5],[6,7,8],[3,5,6]])
print("Original array:",x)
print("Sum of all elements:",np.sum(x))
print("Sum of each column:",np.sum(x, axis=0))
print("Sum of each row:",np.sum(x, axis=1))


Original array: [[1 3 5]
 [6 7 8]
 [3 5 6]]
Sum of all elements: 44
Sum of each column: [10 15 19]
Sum of each row: [ 9 21 14]


Answer 4) Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

In [3]:
import numpy as np
a=float(input("Enter a ="))
b=float(input("Enter b ="))
print("Output of adding a & b:", np.add(a,b))
print("Output of subtracting a from b:",np.subtract(a,b))
print("Output of multiplying a & b:",np.multiply(a,b))
print("Output of dividing a by b:",np.divide(a,b))

Enter a =5
Enter b =10
Output of adding a & b: 15.0
Output of subtracting a from b: -5.0
Output of multiplying a & b: 50.0
Output of dividing a by b: 0.5


Answer 5) Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
degree.

In [25]:
import numpy as np
from array import *
Arr_Angles = []

n=int(input("Enter the number of angles to be entered in an array:"))

for i in range(n):
  x=float(input("Enter next angle in degrees"))
  Arr_Angles.append(x)
InputAngles = np.array(Arr_Angles)
print(InputAngles)
print("sine: array of angles given in degrees")
print(np.sin((InputAngles)*np.pi/180))
print("cosine: array of angles given in degrees")
print(np.cos((InputAngles)*np.pi/180))
print("tangent: array of angles given in degrees")
print(np.tan(InputAngles*np.pi/180))

Enter the number of angles to be entered in an array:4
Enter next angle in degrees30
Enter next angle in degrees45
Enter next angle in degrees60
Enter next angle in degrees90
[30. 45. 60. 90.]
sine: array of angles given in degrees
[0.5        0.70710678 0.8660254  1.        ]
cosine: array of angles given in degrees
[8.66025404e-01 7.07106781e-01 5.00000000e-01 6.12323400e-17]
tangent: array of angles given in degrees
[5.77350269e-01 1.00000000e+00 1.73205081e+00 1.63312394e+16]


Answer 6) Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
index labels

In [26]:
import pandas as pd
import numpy as np

Student = {'Name': ['Ram', 'Rahim', 'Rini', 'James', 'Felix', 'Melinda', 'Amar', 'Abid', 'Anand', 'Micheal'],
        'Age': [23, 25, 29, np.nan, 23, 27, 28, np.nan, 26, 27],
        'Rating': [9, 8, 7, 6, 7.5, 8, 6.5, 9.5, 5, 6]}
labels = [1,2,3,4,5,6,7,8,9,10]

df = pd.DataFrame(Student , index=labels)
print(df)

       Name   Age  Rating
1       Ram  23.0     9.0
2     Rahim  25.0     8.0
3      Rini  29.0     7.0
4     James   NaN     6.0
5     Felix  23.0     7.5
6   Melinda  27.0     8.0
7      Amar  28.0     6.5
8      Abid   NaN     9.5
9     Anand  26.0     5.0
10  Micheal  27.0     6.0


Answer 7) Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [29]:
import pandas as pd
import numpy as np

Student = {'Name': ['Ram', 'Rahim', 'Rini', 'James', 'Felix', 'Melinda', 'Amar', 'Abid', 'Anand', 'Micheal'],
        'Age': [23, 25, 29, np.nan, 23, 27, 28, np.nan, 26, 27],
        'Rating': [9, 8, 7, 6, 7.5, 8, 6.5, 9.5, 5, 6],
        'Score' : [250,240,260,270,280,290,230,220,255,260]}
labels = [1,2,3,4,5,6,7,8,9,10]

df = pd.DataFrame(Student , index=labels)
print("Select specific columns:")
print(df[['Name', 'Score']])

Select specific columns:
       Name  Score
1       Ram    250
2     Rahim    240
3      Rini    260
4     James    270
5     Felix    280
6   Melinda    290
7      Amar    230
8      Abid    220
9     Anand    255
10  Micheal    260


Answer 8) Write a Pandas program to join the two given dataframes along rows and assign all data.

In [30]:
import pandas as pd
import numpy as np

Student1 = {'Name': ['Ram', 'Rahim', 'Rini', 'James', 'Felix'],
        'Age': [23, 25, 29, np.nan, 23],
        'Rating': [9, 8, 7, 6, 7.5],
        'Score' : [250,240,260,270,280]}
labels1 = [1,2,3,4,5]

Student2 = {'Name': ['Melinda', 'Amar', 'Abid', 'Anand', 'Micheal'],
        'Age': [27, 28, np.nan, 26, 27],
        'Rating': [8, 6.5, 9.5, 5, 6],
        'Score' : [290,230,220,255,260]}
labels2 = [6,7,8,9,10]

StudentData1 = pd.DataFrame(Student1 , index=labels1)
StudentData2 = pd.DataFrame(Student2 , index=labels2)

StudentEquivalentData = pd.concat([StudentData1, StudentData2])
print(StudentEquivalentData)

       Name   Age  Rating  Score
1       Ram  23.0     9.0    250
2     Rahim  25.0     8.0    240
3      Rini  29.0     7.0    260
4     James   NaN     6.0    270
5     Felix  23.0     7.5    280
6   Melinda  27.0     8.0    290
7      Amar  28.0     6.5    230
8      Abid   NaN     9.5    220
9     Anand  26.0     5.0    255
10  Micheal  27.0     6.0    260


Answer 9) Write a Pandas program to detect missing values of a given DataFrame. Display True or False.

In [36]:
import pandas as pd
import numpy as np

Student = {'Name': ['Ram', 'Rahim', 'Rini', 'James', 'Felix', 'Melinda', 'Amar', 'Abid', 'Anand', 'Micheal'],
        'Age': [23, 25, 29, np.nan, 23, 27, 28, np.nan, 26, 27],
        'Rating': [9, 8, 7, 6, np.nan, 8, np.nan, 9.5, 5, 6],
        'Score' : [250,240,260,np.nan,280,290,230,np.nan,255,260]}
labels = [1,2,3,4,5,6,7,8,9,10]

StudentData = pd.DataFrame(Student , index=labels)
print("Original Data:")
print(StudentData)

print("Check the data missing in given data return False if data is not present else true:")
print(StudentData.isna())

Original Data:
       Name   Age  Rating  Score
1       Ram  23.0     9.0  250.0
2     Rahim  25.0     8.0  240.0
3      Rini  29.0     7.0  260.0
4     James   NaN     6.0    NaN
5     Felix  23.0     NaN  280.0
6   Melinda  27.0     8.0  290.0
7      Amar  28.0     NaN  230.0
8      Abid   NaN     9.5    NaN
9     Anand  26.0     5.0  255.0
10  Micheal  27.0     6.0  260.0
Check the data missing in given data return False if data is not present else true:
     Name    Age  Rating  Score
1   False  False   False  False
2   False  False   False  False
3   False  False   False  False
4   False   True   False   True
5   False  False    True  False
6   False  False   False  False
7   False  False    True  False
8   False   True   False   True
9   False  False   False  False
10  False  False   False  False


Answer 10) Write a Pandas program to create and display a one-dimensional array-like object containing an array of
data.

In [38]:
import pandas as pd
Animals = pd.Series(["cow", "dog", "tiger", "lion", "monkey"])
print(Animals)

0       cow
1       dog
2     tiger
3      lion
4    monkey
dtype: object
