<a href="https://colab.research.google.com/github/JayeshHarjule/LetsUpgradeAI-ML/blob/master/Day30.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Answer 1)**

**Problem Statement:**

Using Digit dataset and perform the Logistic Regression.

In [1]:
from  sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import metrics

digits = load_digits()
digits.data.shape

(1797, 64)

In [2]:
digits.target.shape

(1797,)

In [4]:
from sklearn.datasets import load_digits

#load the digits data and few EDA
digits = load_digits()
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 5620
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [10]:
from sklearn.linear_model import LogisticRegression    #Logistic Regression
from sklearn.model_selection import train_test_split

#----------------Logistic Regression
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, stratify=digits.target, random_state=0,train_size = 0.25)

logisticRegr = LogisticRegression()
logisticRegr.fit(X_train, y_train)
y_pred=logisticRegr.predict(X_test)

import pandas as pd
df_predicted=pd.DataFrame()
df_predicted['Actual']=y_test
df_predicted['Predicted']=y_pred
df_predicted.head()

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


Actual  Predicted
0       8          8
1       4          4
2       3          3
3       4          4
4       6          6

In [11]:
import numpy as np
mislabel = np.sum((y_test!=y_pred))
print("Total number of mislabelled data points from {} test samples is {}".format(len(y_test),mislabel))

Total number of mislabelled data points from 1348 test samples is 75


In [12]:
# Calculate accuracy
from sklearn.metrics import accuracy_score
print("Accuracy of test set=",accuracy_score(y_test, y_pred)*100)

Accuracy of test set= 94.43620178041543


In [13]:
# Returns a NumPy Array 
# Predict for One Observation (image)
logisticRegr.predict(X_test[0].reshape(1,-1))

array([8])

In [14]:
# Predict for Multiple Observations (images) at Once
logisticRegr.predict(X_test[0:10])

array([8, 4, 3, 4, 6, 3, 2, 6, 3, 2])

In [16]:
# Make predictions on entire test data
predictions = logisticRegr.predict(X_test)
predictions.shape

(1348,)

In [17]:
# Use score method to get accuracy of model
score = logisticRegr.score(X_test, y_test)
print(score)

0.9443620178041543


In [31]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[131   0   0   0   2   0   0   0   0   0]
 [  0 128   0   3   1   1   0   0   3   1]
 [  0   4 128   0   0   0   0   0   1   0]
 [  0   1   0 126   0   4   0   2   2   2]
 [  0   0   0   0 132   0   0   0   1   3]
 [  0   0   1   1   1 128   1   0   0   5]
 [  2   5   0   0   1   0 127   0   1   0]
 [  0   2   0   0   0   0   0 128   0   4]
 [  0   6   2   1   0   0   2   0 117   2]
 [  0   0   0   2   0   2   0   0   3 128]]
